INSERT INTO ad_tab(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab, parent_column_id)
  VALUES(1106001, 0, 0, 'Y', '2011-11-10 16:51:22.0', 100, '2011-11-10 16:51:22.0', 100, 'CFOP', NULL, NULL, 1000012, 135, 25, 1, 'N', 'N', 'N', 'N', 1000298, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'U', NULL, NULL, NULL, 'Y', 'N', NULL);

INSERT INTO ad_tab_trl(ad_tab_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, commitwarning, istranslated)
  VALUES(1106001, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:22.0', 100, '2011-11-10 16:51:22.0', 100, 'CFOP', NULL, NULL, NULL, 'N');

INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106029, 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'CFOP Line', 'Primary key table LBR_CFOPLine', 'Primary key table LBR_CFOPLine', 'Y', 1106001, 1000276, NULL, 'N', NULL, 22, 'N', NULL, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106016, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Organization', 'Organizational entity within client', 'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 'Y', 1106001, 1000277, NULL, 'Y', NULL, 22, 'N', 20, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106015, 0, 0, 'Y', '2011-11-10 16:51:32.0', 100, '2011-11-10 16:51:32.0', 100, 'Client', 'Client/Tenant for this installation.', 'A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.', 'Y', 1106001, 1000278, NULL, 'Y', NULL, 22, 'N', 10, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106018, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Active', 'The record is active in the system', 'There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.', 'Y', 1106001, 1000279, NULL, 'Y', NULL, 1, 'N', 40, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106017, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:52:17.0', 100, 'CFOP', 'Primary key table LBR_CFOP', 'Primary key table LBR_CFOP', 'Y', 1106001, 1000284, NULL, 'Y', NULL, 22, 'N', 51, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106021, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Destination Type', 'Defines the Destination Type', 'Defines the Destination Type', 'Y', 1106001, 1000286, 125, 'Y', NULL, 1, 'N', 70, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106023, 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Product Category', 'Primary key table LBR_ProductCategory', 'Primary key table LBR_ProductCategory', 'Y', 1106001, 1000287, 106, 'Y', NULL, 22, 'N', 90, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106019, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:52:23.0', 100, 'Document Type', 'Document type or rules', 'The Document Type determines document sequence and processing rules', 'Y', 1106001, 1000298, 125, 'Y', NULL, 22, 'N', 30, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106022, 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Is Substituicao Tributaria', 'Defines the Is Substituicao Tributaria Status', 'Defines the Is Substituicao Tributaria Status', 'Y', 1106001, 1000299, 125, 'Y', NULL, 1, 'N', 80, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106020, 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Transaction Type', 'Defines the Transaction Type', 'Defines the Transaction Type', 'Y', 1106001, 1000300, 125, 'Y', NULL, 3, 'N', 60, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106024, 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Is Manufactured', 'Defines if the Product is Manufactured', 'Defines if the Product is Manufactured', 'Y', 1106001, 1000301, 106, 'Y', NULL, 1, 'N', 100, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106025, 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'BPartner Category', 'Primary key table LBR_BPartnerCategory', 'Primary key table LBR_BPartnerCategory', 'Y', 1106001, 1000312, 107, 'Y', NULL, 10, 'N', 110, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106026, 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Brazilian Tax', 'Primary key table LBR_Tax', 'Primary key table LBR_Tax', 'Y', 1106001, 1000317, 111, 'Y', NULL, 22, 'N', 120, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106027, 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'Tax Status', 'Defines the Tax Status', 'Defines the Tax Status', 'Y', 1106001, 1000632, NULL, 'Y', NULL, 2, 'N', 130, NULL, 'Y', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1106028, 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'Legal Message', 'Defines the Legal Message', 'Primary key table LBR_LegalMessage', 'Y', 1106001, 1000642, NULL, 'Y', NULL, 22, 'N', 140, NULL, 'N', 'N', 'N', 'N', 'U', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106024, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Is Manufactured', 'Defines if the Product is Manufactured', 'Defines if the Product is Manufactured', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106028, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'Legal Message', 'Defines the Legal Message', 'Primary key table LBR_LegalMessage', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106018, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Active', 'The record is active in the system', 'There are two methods of making records unavailable in the system: One is to delete the record, the other is to de-activate the record. A de-activated record is not available for selection, but available for reports.
There are two reasons for de-activating and not deleting records:
(1) The system requires the record for audit purposes.
(2) The record is referenced by other records. E.g., you cannot delete a Business Partner, if there are invoices for this partner record existing. You de-activate the Business Partner and prevent that this record is used for future entries.', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106016, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Organization', 'Organizational entity within client', 'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106029, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'CFOP Line', 'Primary key table LBR_CFOPLine', 'Primary key table LBR_CFOPLine', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106023, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Product Category', 'Primary key table LBR_ProductCategory', 'Primary key table LBR_ProductCategory', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106022, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Is Substituicao Tributaria', 'Defines the Is Substituicao Tributaria Status', 'Defines the Is Substituicao Tributaria Status', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106017, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'CFOP', 'Primary key table LBR_CFOP', 'Primary key table LBR_CFOP', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106020, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Transaction Type', 'Defines the Transaction Type', 'Defines the Transaction Type', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106026, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'Brazilian Tax', 'Primary key table LBR_Tax', 'Primary key table LBR_Tax', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106015, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:32.0', 100, '2011-11-10 16:51:32.0', 100, 'Client', 'Client/Tenant for this installation.', 'A Client is a company or a legal entity. You cannot share data between Clients. Tenant is a synonym for Client.', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106021, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Destination Type', 'Defines the Destination Type', 'Defines the Destination Type', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106025, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:34.0', 100, '2011-11-10 16:51:34.0', 100, 'BPartner Category', 'Primary key table LBR_BPartnerCategory', 'Primary key table LBR_BPartnerCategory', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106027, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:35.0', 100, '2011-11-10 16:51:35.0', 100, 'Tax Status', 'Defines the Tax Status', 'Defines the Tax Status', 'N');
INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1106019, 'pt_BR', 0, 0, 'Y', '2011-11-10 16:51:33.0', 100, '2011-11-10 16:51:33.0', 100, 'Document Type', 'Document type or rules', 'The Document Type determines document sequence and processing rules', 'N');
