INSERT INTO ad_column(ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern)
  VALUES(1000628, 0, 0, 'Y', '2008-01-30 08:40:36.0', '2008-01-30 08:40:44.0', 100, 100, 'Profit Percentage', 'Defines the Profit Percentage', 'Defines the Profit Percentage', 0, 'LBRA', 'lbr_ProfitPercentage', 208, 12, NULL, NULL, 10, NULL, 'N', 'N', 'Y', 'Y', NULL, 'N', 0, 'N', 'N', NULL, NULL, NULL, NULL, 'N', 1000249, NULL, 'N', 'N', NULL, NULL, NULL, 'N', 'Y', NULL);

INSERT INTO ad_column_trl(ad_column_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, istranslated)
  VALUES(1000628, 'pt_BR', 0, 0, 'Y', '2010-08-19 16:50:36.206', 100, '2010-08-19 16:50:36.206', 100, 'Margem de Lucro', 'N');

INSERT INTO ad_column(ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern)
  VALUES(1000627, 0, 0, 'Y', '2008-01-30 08:30:18.0', '2008-01-30 08:30:18.0', 100, 100, 'Has Substitution', 'Defines if the record has Substituion', 'Defines if the record has Substituion', 0, 'LBRA', 'lbr_HasSubstitution', 208, 20, NULL, NULL, 1, '''N''', 'N', 'N', 'Y', 'Y', NULL, 'N', 0, 'N', 'N', NULL, NULL, NULL, NULL, 'N', 1000248, NULL, 'N', 'N', NULL, NULL, NULL, 'N', 'Y', NULL);

INSERT INTO ad_column_trl(ad_column_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, istranslated)
  VALUES(1000627, 'pt_BR', 0, 0, 'Y', '2010-08-19 16:50:36.206', 100, '2010-08-19 16:50:36.206', 100, 'Substituição Tributária', 'N');

INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1000428, 0, 0, 'Y', '2008-01-30 08:43:49.0', 100, '2008-01-30 08:44:07.0', 100, 'Has Substitution', 'Defines if the record has Substituion', 'Defines if the record has Substituion', 'Y', 180, 1000627, 1000000, 'Y', NULL, 1, 'N', 570, NULL, 'N', 'N', 'N', 'N', 'LBRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1000428, 'pt_BR', 0, 0, 'Y', '2010-08-19 16:50:36.206', 100, '2010-08-19 16:53:59.109', 100, 'Substituição Tributária', 'Define se o registro possui Substituição Tributária', 'Define se o registro possui Substituição Tributária', 'Y');

INSERT INTO ad_field(ad_field_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, iscentrallymaintained, ad_tab_id, ad_column_id, ad_fieldgroup_id, isdisplayed, displaylogic, displaylength, isreadonly, seqno, sortno, issameline, isheading, isfieldonly, isencrypted, entitytype, obscuretype, ad_reference_id, ismandatory, included_tab_id, defaultvalue, ad_reference_value_id, ad_val_rule_id, infofactoryclass)
  VALUES(1000429, 0, 0, 'Y', '2008-01-30 08:43:49.0', 100, '2008-01-30 08:44:24.0', 100, 'Profit Percentage', 'Defines the Profit Percentage', 'Defines the Profit Percentage', 'Y', 180, 1000628, 1000000, 'Y', '@lbr_HasSubstitution@=''Y''', 10, 'N', 580, NULL, 'Y', 'N', 'N', 'N', 'LBRA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO ad_field_trl(ad_field_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, istranslated)
  VALUES(1000429, 'pt_BR', 0, 0, 'Y', '2010-08-19 16:50:36.206', 100, '2010-08-19 16:53:59.109', 100, 'Margem de Lucro', 'Define a Margem de Lucro', 'Define a Margem de Lucro', 'Y');
