INSERT INTO ad_element(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1106000, 0, 0, 'Y', '2011-07-30 15:15:06.0', 100, '2011-07-30 15:15:06.0', 100, 'lbr_RecalculateTax', 'LBRA', 'Recalculate Tax', 'Recalculate Tax', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ad_element_trl(ad_element_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, printname, description, help, po_name, po_printname, po_description, po_help, istranslated)
  VALUES(1106000, 'pt_BR', 0, 0, 'Y', '2011-07-30 15:15:06.0', 100, '2011-07-30 15:16:21.0', 100, 'Recalcular Impostos', 'Recalcular Impostos', NULL, NULL, NULL, NULL, NULL, NULL, 'N');


INSERT INTO AD_COLUMN(ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern)
  VALUES(1106001, 0, 0, 'Y', '2011-07-30 15:17:20.0', '2011-07-30 15:17:20.0', 100, 100, 'Recalculate Tax', NULL, NULL, 0, 'LBRA', 'lbr_RecalculateTax', 260, 20, NULL, NULL, 1, 'N', 'N', 'N', 'Y', 'Y', NULL, 'N', 0, 'N', 'N', NULL, NULL, NULL, NULL, 'N', 1106000, NULL, 'N', 'N', NULL, NULL, NULL, 'N', 'Y', NULL);
INSERT INTO AD_Column_trl(ad_column_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, istranslated)
  VALUES(1106001, 'pt_BR', 0, 0, 'Y', '2011-07-30 15:17:20.0', 100, '2011-07-30 15:17:20.0', 100, 'Recalculate Tax', 'N');

INSERT INTO AD_COLUMN(ad_column_id, ad_client_id, ad_org_id, isactive, created, updated, createdby, updatedby, name, description, help, version, entitytype, columnname, ad_table_id, ad_reference_id, ad_reference_value_id, ad_val_rule_id, fieldlength, defaultvalue, iskey, isparent, ismandatory, isupdateable, readonlylogic, isidentifier, seqno, istranslated, isencrypted, callout, vformat, valuemin, valuemax, isselectioncolumn, ad_element_id, ad_process_id, issyncdatabase, isalwaysupdateable, columnsql, mandatorylogic, infofactoryclass, isautocomplete, isallowlogging, formatpattern)
  VALUES(1106002, 0, 0, 'Y', '2011-07-30 15:18:15.0', '2011-07-30 15:18:15.0', 100, 100, 'Recalculate Tax', NULL, NULL, 0, 'LBRA', 'lbr_RecalculateTax', 333, 20, NULL, NULL, 1, 'N', 'N', 'N', 'Y', 'Y', NULL, 'N', 0, 'N', 'N', NULL, NULL, NULL, NULL, 'N', 1106000, NULL, 'N', 'N', NULL, NULL, NULL, 'N', 'Y', NULL);
INSERT INTO AD_Column_trl(ad_column_id, ad_language, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, istranslated)
  VALUES(1106002, 'pt_BR', 0, 0, 'Y', '2011-07-30 15:18:15.0', 100, '2011-07-30 15:18:15.0', 100, 'Recalculate Tax', 'N');
